### ISSUE TITLE
Small Grammar Errors "You Be..." 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/active-record-mechanics-crud#11]
Hi there. 
 First line's verb should be "By now you ARE familiar..."  
***
"ORM vs Active Record
By now you be familiar with the concept of an ORM, an Object-Relation Mapper, and should have written something of your own in the Student and InteractiveRecord classes. Our latest iteration was our most powerful yet, it could give us lots of functionality via inheritance."

**Comment by sgharms** [comment]
Fixed by @maxwellbenton
