### ISSUE TITLE
Change gem install active_record to gem install activerecord

### ISSUE THREAD

**Issue by guysbryant** [learn-co-curriculum/active-record-mechanics-crud#12]
The gem is installed via gem install activerecord.

**Comment by drakeltheryuujin** [comment]
Hi @guysbryant,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
