### ISSUE TITLE
Intro to rake lab

### ISSUE THREAD

**Issue by rnhutsko** [learn-co-curriculum/active-record-mechanics-crud#4]
The rake file lab has a part where we run the statement rake greeting:hello from the terminal. Doing so causes an error for me. At first it was a bundle install thing. Did that and still an error posts. The error `rake aborted! Don't know how to build task 'greeting:hello' (see --tasks)`

ATURKEWI SAID 2 MINUTES AGO
Hey Richard!

ATURKEWI SAID 2 MINUTES AGO
So it looks like we need to update this lab a little bit.

ATURKEWI SAID A MINUTE AGO
You can see a list of all possible rake tasks if you run rake -T

ATURKEWI SAID A MINUTE AGO
**## _And we can see there is no rake greeting:hello_**  
RNHUTSKO SAID A MINUTE AGO
yep. That is it.

ATURKEWI SAID A MINUTE AGO
There is just rake hello

**Comment by jjseymour** [comment]
Hey @rnhutsko I am going to close this issue for now. It looks like your solution fixed this issue. Please let me know if that is a mistake and you are still unable to run 'rake greeting:hello' with your code. Thanks!
