### ISSUE TITLE
Add additional info

### ISSUE THREAD

**Issue by nclairesays** [learn-co-curriculum/active-record-mechanics-crud#8]
Hi, I finished reading this page, and went on trying to work on the Mechanics of Migration lab. 

Can you add information in this read me AND in the Mechanics of Migration lab on where to add code to connect to DB and creating table using sql?  I ended up having to skip some of the SQL lessons and went to Active Record lessons first.  Not sure if this information is already obvious through the SQL lessons but can you add info about where to add the following code? The current instructions simply say, "This is how we would connect to a database" and "Let's create our table using SQL:" but it doesn't tell us exactly where the code should be. I think it would be a great help for future students as well. Thanks.

```
connection = ActiveRecord::Base.establish_connection(
  :adapter => "sqlite3",
  :database => "db/students.sqlite"
)
```
and
```
sql = <<-SQL
  CREATE TABLE IF NOT EXISTS students (
  id INTEGER PRIMARY KEY, 
  name TEXT
  )
SQL
 
ActiveRecord::Base.connection.execute(sql)
```

**Comment by sgharms** [comment]
Thank you for your insightful and community-oriented post. We'll look at it ASAP.

**Comment by sgharms** [comment]
We've made an adjustment. Hope this helps.
